### ISSUE TITLE
编译第三方库 ads.pro的时候error: cannot find -lqtadvanceddockingd

### ISSUE THREAD

**Issue by leonjang** [czyt1988/data-workbench#1]
![image](https://github.com/czyt1988/data-workbench/assets/33179543/d89d63c7-b6f7-4ad1-910f-5622f9582d8b)

**Comment by czyt1988** [comment]
用dev分支还是master分支的?

**Comment by czyt1988** [comment]
后续不使用qmake，全部切换为cmake，具体编译过程见文档
